'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useRouter, useParams } from 'next/navigation';
import { api } from '@/lib/api';
import { toast } from 'react-hot-toast';

export default function ReportDetailPage() {
    const { user } = useAuth();
    const router = useRouter();
    const params = useParams();
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (user && params.id) {
            fetchReport();
        }
    }, [user, params.id]);

    const fetchReport = async () => {
        try {
            setLoading(true);
            const response = await api.getReportById(params.id);
            setReport(response.report);
        } catch (error) {
            console.error('Error fetching report:', error);
            toast.error('Failed to load report');
        } finally {
            setLoading(false);
        }
    }; const getReportTypeLabel = (type) => {
        const labels = {
            daily: 'Daily',
            weekly: 'Weekly',
            monthly: 'Monthly',
            yearly: 'Yearly'
        };
        return labels[type] || type;
    };

    const downloadReport = () => {
        if (!report) return;

        const reportText = `
ALIMENTIFY NUTRITION REPORT
${getReportTypeLabel(report.report_type)} Report
Generated: ${new Date(report.generated_at).toLocaleString()}
Period: ${report.start_date} to ${report.end_date}

GOAL STATUS: ${report.goal_achieved ? '✅ ACHIEVED' : '⏳ IN PROGRESS'}

SUMMARY STATISTICS
==================
Total Days in Period: ${report.total_days}
Days Logged: ${report.days_logged} (${((report.days_logged / report.total_days) * 100).toFixed(1)}%)
Total Meals: ${report.total_meals}
Logging Streak: ${report.streak_days} days

NUTRITION AVERAGES
==================
Calories: ${report.avg_calories?.toFixed(0)} kcal/day
Protein: ${report.avg_protein_g?.toFixed(1)}g/day
Carbs: ${report.avg_carbs_g?.toFixed(1)}g/day
Fat: ${report.avg_fat_g?.toFixed(1)}g/day

GOAL COMPLIANCE
===============
Calories Compliance: ${report.calories_compliance_percent?.toFixed(1)}%
Protein Compliance: ${report.protein_compliance_percent?.toFixed(1)}%
Carbs Compliance: ${report.carbs_compliance_percent?.toFixed(1)}%
Fat Compliance: ${report.fat_compliance_percent?.toFixed(1)}%
Days On Target: ${report.days_on_target}/${report.days_logged}

${report.starting_weight ? `
WEIGHT PROGRESS
===============
Starting Weight: ${report.starting_weight?.toFixed(1)} kg
Current Weight: ${report.ending_weight?.toFixed(1)} kg
Change: ${report.weight_change > 0 ? '+' : ''}${report.weight_change?.toFixed(1)} kg
Target Weight: ${report.target_weight?.toFixed(1)} kg
Goal Status: ${report.weight_goal_achieved ? '✅ Reached' : '⏳ In Progress'}
` : ''}

${report.best_day_date ? `BEST DAY
========
Date: ${report.best_day_date}
Compliance: ${report.best_day_compliance?.toFixed(1)}%
` : ''}

${report.notes ? `
NOTES
=====
${report.notes}
` : ''}

--
Generated by Alimentify
Your Nutrition Tracking Partner
    `.trim();

        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `nutrition-report-${report.start_date}-to-${report.end_date}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success('Report downloaded!');
    };

    if (!user) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <p className="text-gray-600">Please log in to view this report</p>
            </div>
        );
    }

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600 mx-auto"></div>
                    <p className="text-gray-600 mt-4">Loading report...</p>
                </div>
            </div>
        );
    }

    if (!report) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center">
                    <p className="text-gray-600">Report not found</p>
                    <button
                        onClick={() => router.push('/my/reports')}
                        className="mt-4 text-green-600 hover:text-green-700 font-semibold"
                    >
                        ← Back to Reports
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50 py-8 px-4 sm:px-6 lg:px-8">
            <div className="max-w-5xl mx-auto">
                <div className="mb-6">
                    <button
                        onClick={() => router.push('/my/reports')}
                        className="text-gray-600 hover:text-gray-900 mb-4 flex items-center gap-2"
                    >
                        ← Back to Reports
                    </button>
                    <div className="flex justify-between items-start">
                        <div>
                            <h1 className="text-3xl font-bold text-gray-900">
                                {getReportTypeLabel(report.report_type)} Nutrition Report
                            </h1>
                            <p className="text-gray-600 mt-2">
                                {report.start_date} to {report.end_date}
                            </p>
                            <p className="text-sm text-gray-500 mt-1">
                                Generated on {new Date(report.generated_at).toLocaleString()}
                            </p>
                        </div>
                        <button
                            onClick={downloadReport}
                            className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors font-semibold shadow-md"
                        >
                            📥 Download Report
                        </button>
                    </div>
                </div>

                <div className={`rounded-xl shadow-lg p-8 mb-6 text-center ${report.goal_achieved ? 'bg-gradient-to-r from-green-500 to-green-600' : 'bg-gradient-to-r from-orange-500 to-orange-600'
                    }`}>
                    <div className="text-white">
                        <h2 className="text-4xl font-bold mb-2">
                            {report.goal_achieved ? '🎉 Goal Achieved!' : '📊 In Progress'}
                        </h2>
                        <p className="text-xl opacity-90">
                            {report.goal_achieved
                                ? 'Congratulations! You met your nutrition goals for this period!'
                                : 'Keep tracking your meals consistently to reach your goals!'}
                        </p>
                    </div>
                </div>

                <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">📊 Summary Statistics</h2>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                        <div className="bg-blue-50 p-4 rounded-lg">
                            <p className="text-sm text-gray-600 mb-1">Total Days</p>
                            <p className="text-3xl font-bold text-blue-700">{report.total_days}</p>
                        </div>
                        <div className="bg-green-50 p-4 rounded-lg">
                            <p className="text-sm text-gray-600 mb-1">Days Logged</p>
                            <p className="text-3xl font-bold text-green-700">{report.days_logged}</p>
                            <p className="text-xs text-gray-500 mt-1">
                                {((report.days_logged / report.total_days) * 100).toFixed(1)}%
                            </p>
                        </div>
                        <div className="bg-purple-50 p-4 rounded-lg">
                            <p className="text-sm text-gray-600 mb-1">Total Meals</p>
                            <p className="text-3xl font-bold text-purple-700">{report.total_meals}</p>
                        </div>
                        <div className="bg-orange-50 p-4 rounded-lg">
                            <p className="text-sm text-gray-600 mb-1">Logging Streak</p>
                            <p className="text-3xl font-bold text-orange-700">{report.streak_days} 🔥</p>
                        </div>
                    </div>
                </div>

                <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">🎯 Nutrition Averages</h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="border border-gray-200 p-4 rounded-lg">
                            <div className="flex justify-between items-center">
                                <span className="text-gray-700 font-semibold">Calories</span>
                                <span className="text-2xl font-bold text-blue-600">
                                    {report.avg_calories?.toFixed(0)} <span className="text-sm text-gray-500">kcal/day</span>
                                </span>
                            </div>
                        </div>
                        <div className="border border-gray-200 p-4 rounded-lg">
                            <div className="flex justify-between items-center">
                                <span className="text-gray-700 font-semibold">Protein</span>
                                <span className="text-2xl font-bold text-green-600">
                                    {report.avg_protein_g?.toFixed(1)} <span className="text-sm text-gray-500">g/day</span>
                                </span>
                            </div>
                        </div>
                        <div className="border border-gray-200 p-4 rounded-lg">
                            <div className="flex justify-between items-center">
                                <span className="text-gray-700 font-semibold">Carbs</span>
                                <span className="text-2xl font-bold text-orange-600">
                                    {report.avg_carbs_g?.toFixed(1)} <span className="text-sm text-gray-500">g/day</span>
                                </span>
                            </div>
                        </div>
                        <div className="border border-gray-200 p-4 rounded-lg">
                            <div className="flex justify-between items-center">
                                <span className="text-gray-700 font-semibold">Fat</span>
                                <span className="text-2xl font-bold text-purple-600">
                                    {report.avg_fat_g?.toFixed(1)} <span className="text-sm text-gray-500">g/day</span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">✅ Goal Compliance</h2>
                    <div className="space-y-4">
                        {[
                            { label: 'Calories', value: report.calories_compliance_percent, color: 'blue' },
                            { label: 'Protein', value: report.protein_compliance_percent, color: 'green' },
                            { label: 'Carbs', value: report.carbs_compliance_percent, color: 'orange' },
                            { label: 'Fat', value: report.fat_compliance_percent, color: 'purple' },
                        ].map((metric) => (
                            <div key={metric.label}>
                                <div className="flex justify-between mb-1">
                                    <span className="text-gray-700 font-semibold">{metric.label}</span>
                                    <span className={`font-bold text-${metric.color}-600`}>
                                        {metric.value?.toFixed(1)}%
                                    </span>
                                </div>
                                <div className="w-full bg-gray-200 rounded-full h-3">
                                    <div
                                        className={`bg-${metric.color}-600 h-3 rounded-full transition-all`}
                                        style={{ width: `${Math.min(metric.value || 0, 100)}%` }}
                                    ></div>
                                </div>
                            </div>
                        ))}
                    </div>
                    <div className="mt-6 bg-gray-50 p-4 rounded-lg">
                        <p className="text-gray-700">
                            <span className="font-semibold">Days On Target:</span> {report.days_on_target}/{report.days_logged}
                            <span className="text-sm text-gray-500 ml-2">
                                (within 10% of target calories)
                            </span>
                        </p>
                    </div>
                </div>

                {report.starting_weight && (
                    <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">💪 Weight Progress</h2>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <div className="text-center">
                                <p className="text-sm text-gray-600 mb-1">Starting Weight</p>
                                <p className="text-2xl font-bold text-gray-900">{report.starting_weight?.toFixed(1)} kg</p>
                            </div>
                            <div className="text-center">
                                <p className="text-sm text-gray-600 mb-1">Current Weight</p>
                                <p className="text-2xl font-bold text-gray-900">{report.ending_weight?.toFixed(1)} kg</p>
                            </div>
                            <div className="text-center">
                                <p className="text-sm text-gray-600 mb-1">Change</p>
                                <p className={`text-2xl font-bold ${report.weight_change > 0 ? 'text-red-600' : 'text-green-600'}`}>
                                    {report.weight_change > 0 ? '+' : ''}{report.weight_change?.toFixed(1)} kg
                                </p>
                            </div>
                            <div className="text-center">
                                <p className="text-sm text-gray-600 mb-1">Target Weight</p>
                                <p className="text-2xl font-bold text-gray-900">{report.target_weight?.toFixed(1)} kg</p>
                            </div>
                        </div>
                        <div className="mt-4 text-center">
                            <span className={`px-4 py-2 rounded-full font-semibold ${report.weight_goal_achieved ? 'bg-green-100 text-green-800' : 'bg-orange-100 text-orange-800'
                                }`}>
                                {report.weight_goal_achieved ? '✅ Weight Goal Reached' : '⏳ Weight Goal In Progress'}
                            </span>
                        </div>
                    </div>
                )}

                {report.best_day_date && (
                    <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">🏆 Best Day</h2>
                        <div className="bg-yellow-50 border-2 border-yellow-300 p-6 rounded-lg text-center">
                            <p className="text-lg text-gray-700 mb-2">
                                Your best day was <span className="font-bold text-yellow-700">{report.best_day_date}</span>
                            </p>
                            <p className="text-3xl font-bold text-yellow-600">
                                {report.best_day_compliance?.toFixed(1)}% Compliance
                            </p>
                        </div>
                    </div>
                )}

                {report.notes && (
                    <div className="bg-white rounded-xl shadow-lg p-6">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">📝 Notes</h2>
                        <p className="text-gray-700 whitespace-pre-wrap">{report.notes}</p>
                    </div>
                )}
            </div>
        </div>
    );
}
